<a href="https://colab.research.google.com/github/HugoStigletz/Data-Analytics-Portfolio/blob/main/Numpy_Array_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [10]:
my_array = np.arange(8)
my_array = np.arange(1, 8)
my_array = np.arange(-1, 9.25, 2)
my_array

array([-1.,  1.,  3.,  5.,  7.,  9.])

In [15]:
#arrays from lists
from_list = np.array([1,2,3], dtype=np.int8)
from_list

array([1, 2, 3], dtype=int8)

In [24]:
# 2D arrays
from_list = np.array([[1,2,3], [4,5,6]], dtype=np.int8)
array_2nd = np.array((np.arange(0,8,2,), np.arange(1,8,2)))
"1D shape:", my_array.shape

('1D shape:', (6,))

In [23]:
"2D shape:", array_2nd.shape

('2D shape:', (2, 4))

In [26]:
# convert to 2 columns and 4 rows
array_2d = array_2nd.reshape((4, 2))
# return to rows
array_2d = array_2nd.reshape((2, 1, 4))
array_2d

array([[[0, 2, 4, 6]],

       [[1, 3, 5, 7]]])

In [28]:
#empty arrays
empty_array = np.zeros((2,2))
empty_array

array([[0., 0.],
       [0., 0.]])

In [30]:
#empty arrays
empty_array = np.ones((8,8))
empty_array

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [31]:
eye_array = np.eye(3)
eye_array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
# will move one diagonal below / (k=1 will go up one diagonal)
eye_array = np.eye(3, k=-1)
eye_array

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [36]:
#set values to to 0
eye_array[eye_array == 0] = 2
eye_array

array([[2., 2., 2.],
       [1., 2., 2.],
       [2., 1., 2.]])

In [38]:
eye_array[eye_array < 2] =9
eye_array

array([[2., 2., 2.],
       [9., 2., 2.],
       [2., 9., 2.]])

In [39]:
#set the first row value
eye_array[0] = 3
eye_array

array([[3., 3., 3.],
       [9., 2., 2.],
       [2., 9., 2.]])

In [40]:
#select first 2 rows
eye_array[:2] =3
eye_array

array([[3., 3., 3.],
       [3., 3., 3.],
       [2., 9., 2.]])

In [41]:
# a 1 in a slicing command will select all 
eye_array[1:] = 3
eye_array

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [42]:
# select the first column
eye_array[:, 0] = 4
eye_array

array([[4., 3., 3.],
       [4., 3., 3.],
       [4., 3., 3.]])

In [43]:
# set last column to 4
eye_array[:, -1] = 4
eye_array

array([[4., 3., 4.],
       [4., 3., 4.],
       [4., 3., 4.]])

In [45]:
# select the last 2 rows and first two clumns 
eye_array[1:, :2] = 9
eye_array

array([[4., 3., 4.],
       [9., 9., 4.],
       [9., 9., 4.]])

In [46]:
# this will arange from the smallest to largest number
eye_array, "\n"
sorted_array = np.sort(eye_array)
sorted_array

array([[3., 4., 4.],
       [4., 9., 9.],
       [4., 9., 9.]])

In [47]:
# with axis=0 we are now aranging by column
eye_array, "\n"
sorted_array = np.sort(eye_array, axis=0)
sorted_array

array([[4., 3., 4.],
       [9., 9., 4.],
       [9., 9., 4.]])

In [48]:
# "MERGESORT" or "HEAPSORT" could result in faster calc. when dealing with much larger data
eye_array, "\n"
sorted_array = np.sort(eye_array, axis=0, kind="mergesort")
sorted_array

array([[4., 3., 4.],
       [9., 9., 4.],
       [9., 9., 4.]])

In [49]:
#copy arrays
my_view = sorted_array.view()
my_copy = sorted_array.copy()

my_view[:] = 4
my_view, "\n"
sorted_array

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [50]:
my_copy = sorted_array.copy()
my_copy

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [51]:
my_view

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])